rlp/rlp.go
rlp/rlp_test.go

There is a bug in the `decodeLength` method where `binary.Uvarint(input[1 : n+1])` fails to return the length of the list *if input[1:n+1] is not an 8 byte array*. This is because `binary.Uvarint` always expects an 8 byte array as an input so it can return a `uint64`. To solve this issue, we must left pad it to 8 bytes (since it uses big-Endian).

rlp: Fix bug in decodeLength code

---

rlp/rlp.go
rlp/rlp_test.go

Taken from the RLP spec:
> ...but positive RLP integers must be represented in big-endian binary form with no leading zeroes (thus making the integer value zero equivalent to the empty byte array)

rlp: fix length encoding

---

rlp/rlp.go
rlp/rlp_test.go

encoding example:
```go
item := rlp.List(
rlp.Byte(4),
rlp.List(
rlp.Bytes(src.Ip[:]),
rlp.Uint16(src.UdpPort),
rlp.Uint16(src.TcpPort),
),
rlp.List(
rlp.Bytes(dest.Ip[:]),
rlp.Uint16(dest.UdpPort),
rlp.Uint16(dest.TcpPort),
),
rlp.Time(time.Now().Add(time.Hour)),
)
```
decoding example:
```go
item, err := rlp.Decode(packet[headerSize:])
if err != nil {
return err
}
hash, err := item.At(1).Hash()
if err != nil {
return err
}
```

rlp: refactor interface

---

go.mod
go.sum
isxsecp256k1/secp256k1.go
isxsecp256k1/secp256k1_test.go

The interface in this package uses fixed length arrays -- which may turn out to be annoying. But I had this thought that having the compiler check input/output sizes would ultimately lead to safer crypto code.

isxsecp256k1: new package

---

rlp/rlp.go
rlp/rlp_test.go
rlp/types.go

The 0 byte is 0x80 in every other rlp encoding lib. 
Even though the spec doesn't call this out specifically, 
it should be similar to int 0 and the empty string.

rlp: fix encoding 0 byte. refactor type helpers

---

isxhash/keccak.go

Similar to #16.
I'm up in the air about this package and the isxsecp256k1 package. One one hand, it's nice to have the crypto related functions well constructed in small packages so that fewer mistakes can be made, and OTOH it seems silly, and npmish, to have such small packages in the tree. We'll see how this goes.

isxhash: new package

---

rlp/rlp.go
rlp/rlp_test.go
rlp/types.go

We have a pretty great function for turning integers into byte slices. So we can use that instead of stitching together various stdlib functions.

rlp: refactor. use encodeUint for type helpers

---

bint/binary_test.go
bint/bint.go

Since we have to be specific with "no leading zeros" in our protocol work, I've found this package much easier to work with than the std lib's binary package.

bint: new package

---

rlp/rlp.go
rlp/rlp_test.go
rlp/types.go

One big change here is that Encode now has to account for the 0 byte --which is 0x80 per the RLP spec. Previously, we were relying on integer encoding return an empty byte array for 0. However, bint encode 0 as [0x00].

rlp: use bint package for integer encoding

---

bint/binary_test.go
bint/bint.go
rlp/rlp.go
rlp/types.go

The length can easily be checked by calling len() on the returned bytes. 
In the case where the caller is passing a pre-allocated buffer, 
the caller may already know the length without calling len().

bint: simplify encode interface. remove length from return

---

rlp/rlp.go
rlp/rlp_test.go

In the case that the input to Decode contains more bytes than is specified by the RLP header, we simply ignore those bytes instead of returning an error.
This is motivated by the fact that the RLPx protocol will add padding around an RLP message. To complicate matters, the padding is random -making it difficult to remove the padding prior to calling rlp.Decode. Therefore, it seems fine and good to have Decode simply ignore trailing data.
This commit also removes an unused test helper function.

rlp: remove too many bytes error

---

rlp/rlp.go
rlpx/handshake.go
rlpx/handshake_test.go

* Parse the auth handshake message to extract the init nonce, remote pub key, and remote ephemeral pub keys
* Send an ack message in response to that
* Finish up tests for the handshake

rlpx: parse auth message and send ack

---

rlp/rlp_test.go

The previous test didn't exercise the following code:
switch {
case len(input[i:]) < listSize:
return Item{}, errTooFewBytes
case len(input[i:]) > listSize:
// It's possible that the input contains
// more bytes that is specified by the
// header's length. In this case, instead
// of returning an error, we simply remove
// the extra bytes.
input = input[:i+listSize]
}
Now it does.

rlp: improve padded list test

---

cmd/xnode/main.go
rlp/rlp_test.go
rlp/types.go
rlpx/rlpx.go

This PR adds a `HandleMessage` method which delegates to the correct handler depending on the `msgId`. It also fixes a bug: we weren't parsing `msgId` correctly before since it's an "RLP-encoded uint64" (so really, the byte `0x80` or [128] should be interpreted as `0` which is the msgId for `Hello`.

rlpx: parse disconnect message and fix msgID bug

---

discv4/discover.go
enr/enr.go
rlp/rlp_test.go
rlp/types.go
rlpx/rlpx.go

bint encoding/decoding: we introduced the bint package after 
adding the rlp package. This commits moves the rlp package 
towards the bint package which eliminates the need for padding.
unused errors: it seems better to not return errors for things 
that have good zero values. Instead, callers can check the 
length of a string or byte slice.

rlp: refactor. remove unused errors. use bint for decoding

---

cmd/xnode/main.go
rlpx/rlpx.go
rlpx/rlpx_test.go

Since compression is omitted only for the Hello message, 
I wanted to have the conditional logic alongside the Hello 
implementation instead of having it in the encode/decode path.
Also, goimports cleaned up some whitespace and ordering.
Finally, I added a quick test for the status message.

rlpx: refactor encode/decode snappy

---

abi/abi.go
abi/abi_test.go
abi/abit/types.go

Uses the abi encoding functionality to parse emitted events from evm logs.
Indexed logs are easy to parse as they are contained in the topics array. However, un-indexed
logs are abi-encoded bytes in the log's data field. The data field needs to be decoded with a
user-supplied schema. The `abit` package can be used to define the decoding schema.
Example:
bxfr, ok := xabi.Match(log, abi.NamedEvent("TransferBatch").
Indexed("operator", abit.Address).
Indexed("from", abit.Address).
Indexed("to", abit.Address).
UnIndexed("ids", abit.List(abit.Uint256)).
UnIndexed("values", abit.List(abit.Uint256)),
)

abi: add function for parsing event logs. s/at/abit

---

abi/abi.go
abi/abit/types.go
abi/abit/types_test.go

Event signatures can contain tuples, a list of tupes, tuples of tuples, 
etc... The Name() method now makes it easy to generate the name
for a type that is ready for ABI signatures.

abi/abit: add abi sig support for type names

---

abi/abi.go
abi/abi_test.go
abi/abit/types.go
abi/abit/types_test.go

The newly added Input.ABIType and abit.Resolve method/function supports the flow of building Event/Input structs from JSON instead of builder methods. It is still possible to build the structs by hand, but it is likely that the majority of use cases will depend on parsing a ABI JSON file and then using that data to call Match functions. In this case, we needed a method to recursively build the abit.Type schema from the JSON.

abi: build type schema from Event/Input structs

---

abi/abi.go
abi/abi_test.go

not totally sure if this is the right approach (casting the uint8 to a uint64). my understanding is that a uint8 abi encodes the same as a uint64 (mostly from playing around with [this site](https://abi.hashex.org)) but as always, i could be misunderstanding something

abi: add uint8 support for encoding/decoding

---

abi/abi.go
abi/abi_test.go
abi/abit/types.go
abi/abit/types_test.go

In preparation for a new abi code generator, we are going to have Match return a tuple item instead of a map of items. The map of items is inherently flawed since it only does a good job of accessing top level inputs. Events with nested data structures were not name-accessible from the map.
To solve the accessibility problem, we will introduce code generation that will act as a thin layer around the Item so that accessing data doesn't require indexing (eg item.At(XXX) and so forth).

abi: refactor. break abi.Match interface

---

abi/abi.go
abi/abi_test.go
go.mod
go.sum

There was a bug when calling Match with an Event that contained non-indexed and indexed inputs. It was a matter of array indexing and the problem is now corrected. Tests have been added that caught the bug.

abi: fix Match for {non-,}indexed returned items

---

abi/abi_test.go
abi/abit/types.go
abi/abit/types_test.go

If a nested tuple contains static fields then it is considered static. A simple, recursive Static check handles this case.

abi: fix static check for nested static tuples

---

abi/abi.go
abi/abi_test.go
abi/abit/types.go
abi/abit/types_test.go

This commit adds support for decoding fixed length lists. The solution also improves the architecture of the code as it leverages tuple decoding instead of doing it's own decoding. This means we can remove the Size method on abit.Type. After all, the ABI spec instructs implementations to treat lists as tuples.

abi: bugfix for fixed length list decoding

---

abi/abig/gen.go

The template doesn't call `itemFunc` for lists or tuples.

abi/abig: remove unused code

---

abi/abi.go

These slice methods were added for DX. Now that genabi exists, for optimal DX, users should generate structs using genabi.
For machine optimized access to decoded items, users can still access
the data with: At, Len, etc.

abi: remove unused code

---

abi/abi.go
abi/abi_test.go

The prior code assumed that each field's header is 32 bytes --which is correct for elementary static types, and for dynamic types, but is incorrect for nested static tuples or static size arrays with static elements.
This patch leverages the fact that the type's Size field is recursively computed so that we account for arbitrary nesting.

abi: bugfix. encoding dynamic after wide static

---

genabi/example/example.go
genabi/example/example.json
genabi/example/example_test.go
genabi/gen.go
genabi/template.txt

The underlying abi code supports this feature so this change addresses the generated code. In particular, we have to deal with reversing the array notation and avoiding calls to make since arrays aren't created using make.

genabi: add support for fixed size arrays

---

genabi/gen.go
genabi/template.txt

Without this code, capitalized strings in the abi json file would be exported in generated code.

genabi: don't accidently export generated vars

---

abi/abi.go
abi/abi_test.go
genabi/example/example.go
genabi/template.txt

It is not uncommon for ethereum calldata to include an abi encoded payload with extra bytes appended. In order to seperate the abi encoded data from the extra bytes, Decode will return the number of bytes read so that callers can safely extract the extra bytes.
This commit adds a test to ensure that Decode will work with input that contains extra bytes.

abi: return number of bytes read from abi.Decode

---

abi/abi.go
abi/abi_test.go
abi/item.go

In the case of a dynamic, elementary types, the nbytes calculation works only when length > 0.
If length == 0, return early and don't use the nbytes calculation.

abi: bugfix. elementary, dynamic types of length 0

---

abi/schema/schema.go
abi/schema/schema_test.go

this adds a test for an ABI with spaces, which is failing before I added the line that removes spaces before parsing. let me know if there's a better way that you'd like to accomplish this!

abi/Parse: allow for extra spaces in schema definitions

---

bloom/bloom.go
bloom/bloom_test.go

Implements the special Bloom filter used for log data as described in the [Ethereum Yellowpaper](https://ethereum.github.io/yellowpaper/paper.pdf) (page 10)

bloom: new pkg. Sketch out logs bloom filter for events

---

bloom/bloom.go

bloom: fix spelling in docs

---

.github/workflows/go-mod-tidy.yml
.github/workflows/go-test.yml
go.mod

This pull request adds an action that ensures go mod tidy has been run.
We could add it in as part of the `go test` action - bit of personal preference here with regards to wanting to break it out. Happy to just add the step to the end if you prefer.
The primary reason why I like having `go mod tidy` be a separate workflow is that it's useful as a reviewer or committer to know at a glance if the test is failing / the code doesn't build vs someone just needs to run `go mod tidy`.

.github: add `go mod tidy` action

---

genabi/gen.go

the [solidity docs](https://docs.soliditylang.org/en/v0.8.19/abi-spec.html) specify that solidity has support
for uints with `M` bits, where `0 < M <= 256` and
`M % 8 == 0`.

genabi: add complete uint support

---

genabi/example/example.go
genabi/example/example.json
genabi/example/example_test.go
genabi/template.txt

the list template was previously producing code that looked like this for `[]address` types (and other non tuple list types)
```go
targetsItem0 := item.At(2)
targets0 := make([][20]byte, targetsItem0.Len())
for i0 := 0; i0 < targetsItem0.Len(); i0++ {
targets0[i0] = targetsItem0.Address()
}
```
which didn't work because on the line where `targetsItem0.Address()` is called, no index to the list is actually passed. causing the data to not scan correctly
this pull request passes in the index to the list generation code, which now produces code of this shape:
```go
targetsItem0 := item.At(2)
targets0 := make([][20]byte, targetsItem0.Len())
for i0 := 0; i0 < targetsItem0.Len(); i0++ {
targets0[i0] = targetsItem0.At(i0).Address()
}
```
tested this and it worked with the contract that i was …

genabi: bugfix. decoding non-tuple arrays

---

.github/workflows/go-mod-tidy.yml
.github/workflows/go-test.yml

the checkout@v2 action is deprecated as it uses node 12.
this pr updates to v3, which is not deprecated

.github/chore: move off deprecated worker action

---

discv4/discover.go
enr/enr.go
rlp/rlp.go
rlp/rlp_test.go
rlp/types.go
rlpx/rlpx.go

I don't like using sync.Pool as a band aid for performance. The extra complexity of pointers and the opaque nature of sync.Pool makes reasoning about GC performance more difficult than it ought to be.
In the particular case of RLP decoding, the actual problem is that we blindly decode nested structures. This wholesale decoding leads more allocations than may be necessary. Instead, there should be an API that allows callers to decode one "level" at a time. This reduces computation and allocations at the cost of a little more work on the caller's behalf.
A forthcoming pull request will contain this new API.
Revert "rlp: use sync.Pool for Items"
This reverts commit d4a1fafd415f74032ecf91608ab3a4dc30f70b10.
Revert "rlp: use pointers to rlp Items"
This reverts commit …

rlp: use values instead of pointers

---

rlp/rlp.go

Under the hood, bytes.Equal does the following:
return string(a) == string(b) bytes.go:20
This is inefficient since we only care if the entire input is equal to:
[]byte{0x80}

rlp: performance. compare single byte instead of string

---

discv4/discover.go
enr/enr.go
rlp/rlp.go
rlp/rlp_test.go
rlpx/rlpx.go

Commit 647880db introduced a more effeciant way of dealing with RLP encoded data. This commit goes back to clean up the implementation. It also fixes a design bug. In the process of ditching the Item struct, we lost the ability to properly encode lists of lists. This commit changes the encoding API slightly, and to be honest, it's not my favorite.
The problem with EncodeList is that it blindly called Encode on each input -- which is obviously not the right thing to do for an already-encoded-list.
The solution I came up with is to provide 2 encoding functions. Both functions take homogeneous arguments. In the case of Encode, it only takes non-encoded, single values. In the case of List, it only takes already encoded values. I added some sugar to Encode such that you can encode a set of …

rlp: clean up Iterator

---

cmd/fz/main.go
gethdb/freezer.go

I used this to extract a subset of block data from a full node. I created a tar file containing the indexes and data for blocks: 16,000,000 to 16,500,000. It ended up being about 10GB. I will use this for local development and benchmarking. Future devs can also download this data set to quickly get up to speed on testing.

cmd/fz: new program for querying freezer files

---

cmd/e2pg/dashboard.go
cmd/e2pg/main.go
docs/e2pg/readme.md
e2pg/e2pg.go
e2pg/e2pg_test.go
e2pg/schema.sql
integrations/testhelper/helper.go

Driver never really made sense to me. As we move the codebase to a place where there are multiple chains and multiple concurrent indexing operations, it became urgent to find a better name. I considered "index" or "job" but ended up enjoying "task" the most. For example:
> To index a new chain, create a new task and configure it with the chain id, integrations, and start/end block.
> E2PG can run multiple tasks concurrently.
> To backfill a particular contract, create a new, temporary task and
configure it with the contract integation and the start/stop block.

e2pg: s/driver/task

---

cmd/e2pg/config.json
e2pg/config/config.go

When configuring a task, you can set eth or pg with a '$' prefixed value indicating that the value is the name of an env var that contains the URL.

e2pg/config: add support for reading eth/pg urls from env

---

cmd/dumpschema/main.go
cmd/e2pg/config.json
cmd/e2pg/main.go
docs/e2pg/readme.md
e2pg/config/config.go
e2pg/migrations.go
e2pg/schema.sql
pgmig/migrate.go
pgmig/migrate_test.go

Adds a file at e2pg/migrations.go which holds all of E2PG's migrations.
The e2pg/schema.sql file is now generated from the migrations file via
the dumpschema command.
Users should call dumpschema after adding a migration to the migrations
file. If this doesn't happen the the GH action test will likely fail.
Migrations can be skipped using the -skip-migration E2PG flag.

e2pg: add system for migrating database

---

e2pg/migrations.go

Unfortunately this constraint isn't valid because erc1155 transfers can result in multiple rows being created for a single tx/log.

e2pg/migrations: remove nft_transfers unique constraint

---

cmd/e2pg/main.go
e2pg/e2pg.go

The core structs (ie Header, Transaction, Receipt) had a mix of owned and borrowed data. The byte slices were pointers to data that were allocated lower in the stack while the uint64s were allocated within the struct. I am exploring moving to a model where instead of keeping long lived buffers in the lower parts of the stack, we use temporary buffers and copy the data into the core structs. This means that we can more easily tune allocations lower in the stack because they don't need to worry about keeping the data around after they've done their job.
Finally, this change actually fixes a memory leak when e2pg is connected to RLPS. Since rlps.LoadBlocks uses io.ReadAll it would allocate the byte slice and then assign pointers to the byte slice onto the core structs. This meant that the …

e2pg: copy data into core structs instead of copying pointers

---

rlps/rlps.go

As of today the CDN doesn't cache data since it's likely to serve invalid data in the case of a reorg.
The scenario:
E2PG has block {n:1 hash:a parent:z} and then requests block {n:2}.
E2PG requests {n:2}
E2PG stores block {n:2 hash:b parent:a}
Eth reorgs and {n:2} becomes {n:2 hash:c parent:a}
E2PG deletes {n:2 hash:b parent:a}
E2PG requests {n:2}
At this point the CDN will serve: `{n:2 hash:b parent:a}`
The fix:
E2PG has block {n:1 hash:a parent:z} and then requests block {n:2}.
E2PG requests hash for {n:2}
E2PG requests {n:2 hash:b}
E2PG stores block {n:2 hash:b parent:a}
Eth reorgs and {n:2} becomes {n:2 hash:c parent:a}
E2PG deletes {n:2 hash:b parent:a}
E2PG requests hash for {n:2}
E2PG requests {n:2 hash:c}
E2PG stores block {n:2 hash:c parent:a}
The RLPS server code will ignore …

rlps: client sends hash to avoid cached reorg blocks

---

e2pg/e2pg.go
e2pg/e2pg_test.go
integrations/erc1155/transfer.go
integrations/erc20/transfer.go
integrations/erc4337/userop.go
integrations/erc721/transfer.go

When a task indexes a batch of blocks it records the highest block number in the task table. If a block within a batch is removed via reorg then it is possible for integrations to contain rows relating to a block that isn't present in the task table. In this case the integrations rows are never removed.
To address this problem, the integrations will now receive a block height that is to be removed and the integrations will delete all rows above and including that block height.

e2pg: use block number for reorg instead of hash

---

cmd/keccak/main.go
cmd/rlpq/main.go

RLPQ returns RLP encoded data for: headers, bodies, and receipts. Keccak will hash the stdin/arg
Query a block hash
```
% rlpq -c 1 -b 17921490  | keccak                       
17a3ea106158267e8d0fae90e8f6810af9e2e380ec11a832318f35754ae820a5
```
Query a transaction hash
```
% rlpq -c 1 -b 17921490  -t 120 | keccak
394405d436baad9d6f5f3d51763bab688322d2da5ca0afd0293754e2986f4d14
```
Query a transaction receipt
```
% rlpq -c 1 -b 17921490  -t 120 -r         
f9fd81f9095a018...
```

cmd/{rlpq,keccak}: new commands for debugging rlps

---

cmd/e2pg/main.go
e2pg/e2pg.go

Deploys, or operational errors, can lead to multiple E2PG processes running at a single time. This causes duplicated work but because of the databases unique constraints there are no corruption issues. However, it is best to avoid these duplication errors as it can be confusing to deployment tooling and its operator.
Fixes #151

e2pg: use pg_advisory_lock to limit 1 process per task

---

e2pg/migrations.go
e2pg/schema.sql

We specify an order on number since our primary query on this table uses a ORDER BY number LIMIT 1 statement. This means that the relation should not need to be sorted at query time.

e2pg/migrations: create index on task table

---

e2pg/e2pg.go
e2pg/migrations.go
e2pg/schema.sql
integrations/testhelper/helper.go
pgmig/migrate.go
pgmig/migrate_test.go

This commit requires a database reset.
All of e2pg's internal tables will be located in the e2pg schema. Tables that are created from events will remain in the public schema.

e2pg: move migrations,task into e2pg schema

---

abi2/abi2.go
cmd/e2pg/dashboard.go
cmd/e2pg/main.go
e2pg/config/config.go
e2pg/config/integration_test.go
e2pg/config/testdata/erc721.json
e2pg/e2pg.go
e2pg/e2pg_test.go
e2pg/migrations.go
e2pg/schema.sql
integrations/testhelper/helper.go
jrpc2/client.go
jrpc2/client_test.go
rlps/rlps.go
rlps/rlps_test.go

This is part of a larger change in E2PG. Instead of users defining tasks, E2PG builds tasks based on user configured integrations.
Each chain (defined in the Ethereum Sources field in the config) will have a main task. Integrations that are following the chain will be processed in the main task. If an integration requires a backfill, a new task will be created. Backfills are not a part of this commit and will be added later. Backfills will need to coordinate to not overlap work with the main task.
Given this archetecture, a task id can simple be: the chain id, a string tag that is one of 'main' 'backfill' and an optional backfill string tag that is unique amongst other backfills on the chain. For example:
1-main
1-backfill-foo

e2pg: use stable task id

---

eth/types.go

tx.value was not being parsed correctly due to a typo. After putting in this change, tx.value stopped showing up as 0

eth/types: fix json tag on Tx.Value

---

eth/types.go
eth/types_test.go

Since the Tx is reused during batch processing, it's possible for the value to accumulate data from prior use. The Bytes.Write function correctly resized the underlying slice prior to decoding but the UnmarshalJSON did not. Now it does.

eth: bugfix. ensure Bytes are reset during unmarshal

---

abi2/abi2.go

Right now the code checks for exact matches, it would be better to check for partial matches

abi2: op_filter 'contains' to use bytes.Contains instead of bytes.Equal

---

abi2/abi2.go
cmd/e2pg/main.go
e2pg/e2pg.go
e2pg/e2pg_test.go
e2pg/integration_test.go
e2pg/migrations.go
e2pg/schema.sql
e2pg/web/index.html
e2pg/web/web.go
wctx/ctx.go

This change is needed for the new backfill model. The goal is to remove the notion of creating tasks from E2PG's API. Instead, E2PG will use the config to determine which tasks need to be created. Each ETH source will have a main task and a backfill task. A task will be identified by it's src_name and backfill columns.

e2pg: remove task id

---

cmd/e2pg/main.go
e2pg/e2pg.go
e2pg/iub_test.go
e2pg/migrations.go
e2pg/schema.sql

This table will be used to control backfill tasks. The task table keeps a history of blocks processed, but they are used for detecting a re-organization. It does not track an integration's individual progress.
By introducing the intg table, we now can know the precise set of blocks that an integration has processed.
This will enable a backfill task to group a set of integrations that need backfilling and process block history based on the needs of the integration.
This commit also introduces the notion of e2pg.{task,intg} pruning. We keep around the last 200 blocks for each src_name / src_name,name. This should help keep queries on this table fast while also preserving history for reorgs and debugging.

e2pg: add integration update table

---

abi2/abi2.go
e2pg/integration_test.go
e2pg/testdata/seaport.json

E2PG copies N rows where N is equal to the number of elements in an abi encoded array(s). For example, if you have the following type:
X(uint8,uint8[2])
then, assuming no filters, 2 rows will be inserted into the table. Each row will have the first uint8 and the 1 and 2nd row will have the 0th and 1st element of the abi encoded array respectively.
This change allows the integration to request the array index be copied into the row. Continuing the example, given the following bytes:
000000000000000000000000000000000000000000000000000000000000002a
0000000000000000000000000000000000000000000000000000000000000040
0000000000000000000000000000000000000000000000000000000000000002
000000000000000000000000000000000000000000000000000000000000002b …

abi2: expose array index when decoding abi arrays

---

abi2/abi2.go
abi2/abi2_test.go
e2pg/e2pg.go

In order for the abi2 package to properly delete
data during a reorg, we needed to make sure that we have
intg_name, src_name, and block_num columns available.
Additionally, this code sanitizes user input for table and column names
since we are building sql strings without bind parameters.

abi2: validate integration. add required columns

---

cmd/e2pg/main.go
e2pg/e2pg.go
e2pg/web/web.go

Having the loadTasks and task.Setup function execute within the task manager's mutex is nice because it makes it easy to reason about order of events. In particular, task setup may insert into the intg table for backfill tasks. If there is already a backfill task underway, we are changing the intg table under the feet of the currently running backfill task. It's much simpler to assume that a single writer is writing to the intg table on behalf of a src/task/backfill combination.

e2pg: improve task manager setup

---

cmd/e2pg/main.go
e2pg/e2pg.go
e2pg/e2pg_test.go

The previous code that did concurrent task processing was dodgy at best. There were two problems with the prior approach:
1. The Source was not thread safe
2. The code that divided the blocks amongst the threads was untested and brittle.

e2pg: partition task for concurrent processing

---

abi2/abi2.go
eth/types.go

Right now there's no support for extracting tx_type so I added that in. This is especially useful for Arbitrum chains that support different txn types: https://docs.arbitrum.io/for-devs/concepts/differences-between-arbitrum-ethereum/rpc-methods.
Additionally, the json unmarshaling code incorrectly returns the first byte of a hex string. For example, "0x6a" would return the decimal value 54 because the code returns `hbyte("6")` which is the ascii value of "6".

e2pg: fix tx.type parsing and add extraction support

---

shovel/task.go

Here's the scenario:
2 integrations with identical source. i1 and i2.
i1.start = 10
i1.stop = 15
i2.start = 15
i2.stop = 20
However, i1 is already complete and i2 was just added. The current SetupTask function would have created a backfill task for both of these integrations. SetupTask would have picked the minimum block height 10 as a starting point and a maximum block height 20 as the stopping point.
Since i1 is complete, it's igRange would be: [15,16]. The task would attempt to process blocks 10 through 15 and i1's filter would ignore these blocks since 10 through 15 is <= 15 through 16.
i2 would also ignore blocks 10 through 15 since its igRange is [15, X] where X is the block height at which the main task has started processing.
This means the task would be downloading blocks 10 …

shovel: bugfix. multiple integrations with backfills

---

cmd/shovel/demo.json
dig/dig.go
eth/types.go
go.mod
go.sum
jrpc2/client.go
jrpc2/client_test.go
shovel/glf/filter.go
shovel/glf/filter_test.go
shovel/integration_test.go
shovel/task.go
shovel/task_test.go
shovel/web/web.go

Shovel will inspect your configuration to find which data you are
indexing and it will pick the best set of rpc methods to use (best
meaning the least amount of data transferred) for the task. As it
stands, a task will be limited by the most expensive integration.
The workaround here is you can create multiple eth_sources /
integration sets to split out cheap and expensive indexers.
For example, getting a receipt tx status and a tx_input is the most
expensive set of fields to index since we have to download receipts
and transaction bodies. So if you wanted to index this set of data,
you could create a source and an integration for this specific
combination. Simultaneously, you could create an eth_source/integration
that indexed erc20 transfers. This integration would only use getLogs
-- …

jrpc2: needs based rpc method selector

---

dig/dig.go
indexsupply.com/shovel/docs/index.md
shovel/config/config.go
shovel/task.go
shovel/task_test.go

This feature commit includes 2 major things:
1. Event/block filters can use the database 
2. Integrations can depend on one another
To accomplish 1 we had to thread the database transaction deep
into the dig package. I'm not totally pleased with this pattern
since it will issue N queries for each input that it needs to check.
Ideally we can batch these checks into a single query. We also have
to thread a mutex since we need to hold the lock before we query
and after we scan all the results. Nevertheless, this should work
and not be terrible. But we will make it better in the future.
For 2 we simply check the integration config to see if any filters
depend on other integrations. If they do, we add a list of integration
names as dependencies to the integration. Then, when we are determining …

shovel: integration dependencies

---

shovel/schema.sql

I dropped the `public` schema when trying to reset shovel and then shovel wouldn't start up:
```
Pushing image to registry...
Upload succeeded
DONE
==> Deploying...
migrating integration: FileStore-FileCreated: table "files_created" stmt "create table if not exists files_created(chain_id int, log_addr bytea, block_time int, filename text, pointer bytea, size numeric, metadata text, ig_name text, src_name text, block_num numeric, tx_idx int, log_idx int, abi_idx int2)": ERROR: no schema has been selected to create in (SQLSTATE 3F000)
migrating integration: FileStore-FileCreated: table "files_created" stmt "create table if not exists files_created(chain_id int, log_addr bytea, block_time int, filename text, pointer bytea, size numeric, metadata text, ig_name text, src_name text, block_num …
```

shovel: create public schema if not exists

---

indexsupply.com/shovel/docs/index.md
jrpc2/client.go
shovel-config-ts/jsr.json
shovel-config-ts/package.json
shovel-config-ts/src/index.ts
shovel/config/config.go
shovel/task.go

It is common for free node services to aggressively rate limit requests. This impacts both backfill and incremental indexing.
For backfilling, it is advisable to use low values for batch_size and concurrency. For example: batch_size=10 and concurrency=1.
For incremental indexing, it is now advisable to increase the poll_duration for a source. For example: poll_duration=1s
Both of these knobs will reduce the amount of requests that are sent to a hosted node.

shovel: expose poll duration for eth source

---

indexsupply.com/shovel/docs/_layout.html
indexsupply.com/shovel/docs/index.md

The new version of the docs has Overview and Reference sections. I was always frusterated that there wasn't a canonical description of the Config object. Now that exists as Reference: Config Object. But I felt that even with a Config Object Reference, there needs to be some high level description of the Config Object. So that exists as: Overview: Config.
I also added a few other things.

indexsupply.com/shove/docs: rewrite

---

dig/dig.go
dig/dig_test.go
indexsupply.com/shovel/docs/index.md

Prior to this commit, Shovel would return early when it encountered a failed filter check. However, this is not how Shove is supposed to work. It is supposed to check all filters and pass the tx/event if at least one of the filters evaluated to true.
fixes #262

shovel: bugfix multiple filters per block/event

---

shovel-config-ts/build-instructions.txt
shovel-config-ts/src/index.ts

I was attempting to use [@indexsupply/shovel-config](https://www.npmjs.com/package/@indexsupply/shovel-config) to make a shovel config in TypeScript but was running into type errors.
Upon further investigation, it appeared that the TypeScript types in the `shovel-config-ts` subproject were out of date with the current version of the `shovel` indexer in the repo. Specifically:
* Some of the block data options in `dig.go` were not present in the `BlockDataOptions` type in Typescript (e.g. `tx_contract_address`, `tx_max_priority_fee_per_gas`): 
https://github.com/indexsupply/shovel/blob/cb9264ec081c598c1ceee65ff08485e304b111a2/dig/dig.go#L896-L962
https://github.com/indexsupply/shovel/blob/cb9264ec081c598c1ceee65ff08485e304b111a2/shovel-config-ts/src/index.ts#L52-L73
* The `FilterOp` type …

shovel-config-ts: update types to match documentation

---

shovel-config-ts/src/index.ts

In https://github.com/indexsupply/shovel/pull/277, a feature was introduced which made empty string values `""` in `filter_arg` correspond to `null` when decoded. This change was not reflected in the TypeScript types for the shovel-config-ts config generator; this PR changes the types to allow `filter_arg` to take an empty string value.
When testing my shovel config with the updated types in this PR, I was successfully able to add `""` to a `filter_arg` without type errors.
Something to consider — in [the docs](https://indexsupply.com/shovel/docs/), it says:
> `filter_arg`: Not required when using filter_ref. Use filter_arg when you want to filter on static data. Must be an array of strings. The string values will be decoded depending on the value of comparison. Namely, a string with a 0x …

shovel-config-ts: allow filter_arg to take empty string
