enr/enr.go, enr/enr_test.go, rlp/rlp.go
Introduces the ENR package, which is responsible for marshalling/unmarshaling an Ethereum Node Record as defined in https://eips.ethereum.org/EIPS/eip-778.
This PR is a starting point that implements the unmarshal method.
=> enr: new package

discv4/kademlia.go, discv4/kademlia/table.go, enr/enr.go, go.mod, go.sum
A rough implementation of the Kademlia algorithm for finding/storing node records in the Ethereum discv4 protocol.
=> discv4/kademlia: implementation

rlpx/handshake.go
There is a bug where we interpreted the ack message incorrectly. The pub key is for the **ephemeral** receiver key; instead we were setting it to `h.remotePubKey`. Also I added comments for the auth payload.
=> rlpx: comments and bug fix

discv4/discover.go
We shouldn't pass around `process` which contains a `sync.Mutex` by value so use a pointer receiver instead.
=> discv4: pass around pointer receiver for process

go.mod
=> go.mod: fix imports

abi/abi.go, abi/abit/types.go
fewer chars no loss of meaning
=> abi: rename ElementType to Elem

abi/abi.go
adds slice convenience functions to the other types, in the vein of `BigIntSlice`
=> abi: add slice functions to Item for various types

abi/abi_test.go, abi/abit/types.go, abi/abit/types_test.go
Implement the fixed length list type: `T[k]`
=> abi/abit: Add support for fixed length lists

.github/workflows/go-test.yml
this pull request adds a github workflow that runs `go test` for the repo. nobody asked me to do this but i decided to do it anyway.
=> misc: add github action for running go test

cmd/g2pg/main.go
added a check to ensure remote databases are not absolutely destroyed
=> cmd/g2pg: provide reset flag for initializing pg

cmd/e2pg/config.json, cmd/e2pg/main.go, docs/e2pg/readme.md, e2pg/config/config.go, e2pg/e2pg.go, e2pg/e2pg_test.go, e2pg/schema.sql, integrations/erc1155/transfer.go, integrations/erc721/transfer.go, integrations/testhelper/helper.go, rlps/rlps.go
This commit enables a single E2PG to process blocks from multiple chains.
=> e2pg: multi tasking

e2pg/config/config.go, e2pg/migrations.go, e2pg/schema.sql, integrations/txinputs/inputs.go, integrations/txinputs/inputs_test.go
user requested feature for saving tx input data if it came from a
particular from/to address.
=> integrations/txinputs: new integration

cmd/e2pg/main.go, e2pg/web/add-source.html, e2pg/web/index.html, e2pg/web/web.go
Provide UI for adding Eth sources.
Eth sources loaded from the database are overwritten by sources with the same name loaded from the config file. Sources from the config file are not stored in the database. To get a complete list of sources you must call [config.AllSources]
=> e2pg/web: add source

e2pg/e2pg.go, e2pg/web/index.html, e2pg/web/web.go
This commit also shows the progress value for a task / integration.
=> e2pg/web: use intg table for task/integration updates

cmd/shovel/main.go, shovel/task.go, shovel/web/diag.html, shovel/web/web.go
Visit /diag to see latency and possible errors for connectivity to the postgres database and to all eth sources.
=> shovel/web: add diagnostics endpoint

eth/types.go, shovel/task.go
This may be a classic case of a failed attempt to outsmart the compiler. In a prior version of the program, I was holding on to the task's blocks via `batch` so that I could reduce the amount of txs/logs/topics that needed to be allocated.
However, in recent benchmarking, and in dealing with a nasty memory leak found in and around the jrpc2 client, I found that task.batch was preventing the GC from reducing memory. Once the batch was made ephemeral, the program got faster and the memory usage was reduced.
Consequently, we no longer need to think about resetting data structures. We create new ones. When in GC Rome...
=> shovel: remove batch cache

shovel/schema.sql, shovel/task_test.go
Adds 'shovel.latest' view to schema. This is considered a public view that shovel users can query to see where shovel is in the chain.
This view first finds the latest block height of each src/integration pair. It is possible that the src/integration pairs are different even though they get their data from the same source. This is because a task runs exactly 1 integration and tasks are run concurrently.
To account for this, the latest query selects the min(num) across src/integration paris. However, to account for the fact that a particular integration may be "backfilling" we adjust the query so that it only considers src/integration pairs that are within 10 blocks of the most up-to-date src/integration.
Consequently, shovel.latest doesn't always produce a monotonically increasing …
=> shovel/schema: add latest view query

eth/types.go, jrpc2/client.go, jrpc2/client_test.go
jrpc2.Client structs are shared between shovel tasks and therefore run concurrently. There was a race condition after downloading (possibly cached via bcache) a header and before downloading the logs. This would result in duplicate transactions being added to the block. The duplicated transactions would contain only the requested logs (as opposed to the entire set of the transaction's logs).
In some cases this duplicated data is not a problem because the integration process removes logs that don't match the integration's configured event signature. However, if you have multiple integrations sharing an event signature the integration process will process the log more than once. In this case, the integration will encounter an error when coping the data to the PG table because the table …
=> jrpc2: bugfix. duplicate txs yielding pg unique constraint violation

cmd/shovel/main.go, indexsupply.com/shovel/docs/index.md, shovel/web/web.go
=> shovel: add prometheus metric endpoint

shovel/task.go
Prior to this commit, Shovel would open a PG transaction for each call to Converge. Converge queries for the local and remote latest and decides what is next to index. Shovel then proceeds to download the remote blockchain data and saves the indexed results to various PG tables -- all within the same PG transaction.
The problem with this approach is that a PG transaction is open while downloading blockchain data. If downloading is fast this is no big deal. However, if downloading is slow (ie lots of trace data, or any other reason) then the transaction is open for a while and because of MVCC overall PG performance can degrade. It is generally best practice to minimize the use PG transactions for a minimal amount of time.
This commit splits up the loading from the inserting. This was …
=> shovel: internal change to postgres transaction usage
